### ISSUE TITLE
UnboundLocalError: local variable 'items' referenced before assignment

### ISSUE THREAD

**Issue by DuendeInexistente** [yottu/yottu#1]
```
Traceback (most recent call last):
  File "yottu.py", line 68, in <module>
    curses.wrapper(main)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "yottu.py", line 39, in main
    dlog.msg("Images will be cached in " + Config().get('file.image.directory'))
  File "/home/akel/Sandbox/yottu/lib/Config.py", line 136, in get
    items = self.getSettings()
  File "/home/akel/Sandbox/yottu/lib/Config.py", line 217, in getSettings
    return sorted(items)
UnboundLocalError: local variable 'items' referenced before assignment


```

Getting this on both ubuntu 14 and the latest version of puppy linux.

And these are the contents of debug.log:
```
Fri Sep  1 22:37:22 2017 0
Fri Sep  1 22:37:22 2017 Logging debug output to debug.log
Fri Sep  1 22:37:22 2017 Exception (Level 1): Config: KeyError: 'Main' >>>in getSettings()
Fri Sep  1 22:37:22 2017 Exception (Level 1): UnboundLocalError: local variable 'items' referenced before assignment 
Fri Sep  1 22:37:41 2017 0
Fri Sep  1 22:37:41 2017 Logging debug output to debug.log
Fri Sep  1 22:37:41 2017 Exception (Level 1): Config: KeyError: 'Main' >>>in getSettings()
Fri Sep  1 22:37:41 2017 Exception (Level 1): UnboundLocalError: local variable 'items' referenced before assignment 
```

**Comment by yottu** [comment]
I forgot to set the variable 'items' in case the config file does not exist. Should be fixed in master.

Can also be fixed with:
mkdir -p ~/.config/yottu && echo '[Main]' > ~/.config/yottu/config
